### PR TITLE
fix the README basic example

### PR DESCRIPTION
**Pull request by palako**

### CODE REVIEW

**Comment by jwuensche** [comment]
Hi palako,
thanks for spotting this mistake in the README, I'll merge your changes right away.

**Comment by fin-ger** [comment]
Ehm... @jwuensche I think you were too fast here. This does not look like a bug in the README!

**Comment by fin-ger** [comment]
Ah, nevermind I misread. I thought the import path was related to `cursive_tabs`, but it is not.

**Comment by jwuensche** [comment]
:joy: No problem, I tested before it indeed broke with the previous, must've been the remnant of some old import paths from previous cursive versions.

**Pull request merged**
